data = {

    'AIGODLIKE Community(cupcko)': '幻之境:cupcko',
    'VertexGroupsMirrorTool': '幻之境:顶点组镜像助手',
    'Mirror vertex groups weights, clean vertex groups': '镜像顶点组，清理顶点组',
    'Mirror weights': '镜像顶点组',
    'Mirror vertex groups weights': '镜像顶点组权重',
    'Clear unused': '删除没有使用',
    'Clear zero': '删除权重为零',
    'Mirror completed!': '镜像完毕!',
    'You cannot select both left and right bones simultaneously!': '不能同时选择左右两边的骨骼!',
    'Multiple vertex groups will be mirrored.': '将会镜像多个顶点组',
    'The object does not have vertex groups.': '对象没有顶点组',
    'Delete vertex groups with a total weight of 0 within the vertex group.': '删除权重为0的顶点组',
    'Delete unused vertex groups.': '删除没有使用的顶点组',
    'Mirror method': '镜像方法',
    'Nearest': '最近点',
    'Polyinterp': '面插值',
    'Nearest vertex': '最近的顶点',
    'Nearest face interpolation': '最近的面插值',
    'Mirror direction': '镜像方向',
    'Select mirror direction': '选择镜像方向',
    'Symmetric': '对称',
    'Multiple vertex groups': '多个顶点组',
    'Mirror or symmetrize multiple vertex groups.': '镜像或者对称多个顶点组',
    'Selected': '选中的',
    'Delete vertex groups with a total weight of 0': '删除总权重为0的顶点组',
    'Mirror or symmetrize selected vertex groups (selected bones, in weight paint mode)': '镜像或者对称选中的顶点组(选中的骨骼，需要在权重绘制模式)',
    'When enabled, make the middle bone symmetrical weight; when disabled, mirror the weight between the left and right bones.': '开启时使中间骨骼对称权重，关闭时使左右两边的骨骼镜像权重',
    '(-x arrow<-) Use the weight on the right side +x -> -x': '(-x箭头<-)使用右边权重+x->-x',
    '(+x arrow->) Use the weight on the left side -x -> +x': '(+x箭头->)使用左边权重-x->+x',
    'When left and right are symmetrical, the nearest point effect is better; when they are not symmetrical, use face interpolation.': '左右对称时最近点效果好，左右不对称时使用面插值',
    "Delete unused vertex groups (deformation bones, modifiers), excluding those used by other objects.": '删除没有使用的顶点组（形变骨骼，修改器），不包括被其他物体使用的顶点组',

}
